05-lection3-02-modal: add modal
js-tasks-ru/htmlcss-20240412_ruslan-mullagaliev pull request #11
Opened 2024-04-28 05:14 UTC by ruslannm

2024-04-28 05:15 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-29 11:23 UTC, GSemikozov approved these changes

2024-04-29 11:23 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-04-29 11:24 UTC, GSemikozov requested changes
конфликт

2024-05-02 13:53 UTC, GSemikozov approved these changes

2024-05-02 13:53 UTC, merged