Macro layout mobile
js-tasks-ru/htmlcss-20240412_ruslan-mullagaliev pull request #17
Opened 2024-05-05 04:22 UTC by ruslannm

2024-05-05 04:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-05 13:29 UTC, GSemikozov requested changes

2024-05-05 13:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +@media screen and (min-width: 375px) {
лучше везде поменять на 767

2024-05-05 13:29 UTC, GSemikozov commented on components/container/container.css
> +  max-width: 344px;
лишнее, лучше padding: 0 15px

2024-05-05 13:29 UTC, GSemikozov commented on components/footer/footer.css
> +  .footer__title_component {
.footer_component .footer__title

2024-05-05 13:29 UTC, GSemikozov commented on components/header/header.css
> +  .header_component {
лишние стили

2024-05-05 13:29 UTC, GSemikozov commented on components/preview/preview.css
> +  height: 46px;
а зачем высоту фиксируем?)

2024-05-07 18:14 UTC, ruslannm commented on components/footer/footer.css
> +  .footer__title_component {
исправил и здесь и в ветке component-page

2024-05-08 19:31 UTC, ruslannm commented on components/preview/preview.css
> +  height: 46px;
исправил

2024-05-08 19:54 UTC, GSemikozov requested changes
конфликты

2024-05-08 19:54 UTC, GSemikozov commented on components/container/container.css
> +  height: 100%;
высоту удаляем

2024-05-11 12:33 UTC, GSemikozov approved these changes

2024-05-11 12:34 UTC, merged