07 lection5 04 input
js-tasks-ru/htmlcss-20240412_ruslan-mullagaliev pull request #21
Opened 2024-05-06 14:54 UTC by ruslannm

2024-05-06 14:56 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-07 17:59 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-08 19:31 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-08 19:56 UTC, GSemikozov requested changes

2024-05-08 19:56 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="input"
в случае с инпутом как раз и не надо все заворачивать в лейбл)

2024-05-08 19:56 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        ><p class="input__label">Label</p>
p -> label

2024-05-08 19:56 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          <svg class="input__icon_success" width="24" height="24">
модификатор без своего элемента?

2024-05-08 19:56 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          <svg class="input__icon_error" width="24" height="24">
и тут

2024-05-09 09:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-09 09:50 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-11 12:34 UTC, GSemikozov approved these changes

2024-05-11 12:34 UTC, merged