09-lection-01-burger-menu: add burger-menu
js-tasks-ru/htmlcss-20240412_ruslan-mullagaliev pull request #22
Opened 2024-05-12 11:26 UTC by ruslannm

2024-05-12 11:26 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-13 08:31 UTC, GSemikozov requested changes

2024-05-13 08:31 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__theme {
это отдельный блок, и в данной задаче переключалку темы не надо добавлять. А вот само меню - можно было бы

2024-05-13 08:31 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +      class="burger-menu__open"
это же не часть блока бургер меню, даже по коду видим что элемент снаружи

2024-05-13 08:31 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar__title_burger-menu {
лучше через микс у самого бургер меню

2024-05-13 08:31 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar__content_burger-menu {
и тут

2024-05-15 18:51 UTC, ruslannm commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__theme {
в макете был блок  с темой, после ревью убрал.

2024-05-15 18:51 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-16 12:35 UTC, GSemikozov requested changes

2024-05-16 12:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  transform: translateX(-375px);
а зачем?)
вообще, весь блок по умолчанию и будем прятать / перемещать (а не его элемент __window)

2024-05-16 12:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +    <div class="modal burger-menu" id="burger-menu">
это все-таки не модалка, не надо смешивать

2024-05-16 16:09 UTC, ruslannm commented on 09-lection7/01-burger-menu/burger-menu.css
> +  transform: translateX(-375px);
это было сделано потому что если вьюпорт был меньше 375, то меню начинало вылазить слева.

2024-05-16 16:10 UTC, ruslannm commented on 09-lection7/01-burger-menu/index.html
> +    <div class="modal burger-menu" id="burger-menu">
увидел что на сайте сделано через модалку. Уберу.

2024-05-16 16:59 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-16 17:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-18 13:19 UTC, GSemikozov approved these changes

2024-05-18 13:19 UTC, merged