10 lection8 01 theme changer
js-tasks-ru/htmlcss-20240412_ruslan-mullagaliev pull request #25
Opened 2024-07-18 18:01 UTC by ruslannm

Сделал:
Переключатель темы /10-lection8/01-theme-changer

И в целом весь проект:
Анимация чекбокса
Анимация гистограммы
Анимация скелетона
Переключатель темы

2024-07-18 18:01 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-20 09:23 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-20 20:47 UTC, GSemikozov requested changes

2024-07-20 20:47 UTC, GSemikozov commented on assets/css/blocks/_logo.scss
> +    background: var(--text-primary);
это же про текст, не про фон

2024-07-20 20:47 UTC, GSemikozov commented on assets/css/blocks/_logo.scss
> +    border-bottom: 16px solid var(--text-primary);
и тут) стилизуем не текст а бордер

2024-07-20 20:47 UTC, GSemikozov commented on assets/css/blocks/_typography.scss
>    &_p {
**&_p** -> `&__text` (не стоит подвязываться под конкретный тег, текстовый элемент может быть и div и span)

2024-07-21 04:00 UTC, ruslannm commented on assets/css/blocks/_logo.scss
> +    background: var(--text-primary);
добавил переменную

2024-07-21 08:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-21 16:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-08-25 18:44 UTC, GSemikozov approved these changes

2024-08-25 18:44 UTC, merged